services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: jarvis
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - NODE_ENV=production
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - VITE_WEBHOOK_URL=${VITE_WEBHOOK_URL}
      - VITE_CALLBACK_URL=${VITE_CALLBACK_URL}
      - VITE_SOURCE_NAME=${VITE_SOURCE_NAME}
      - VITE_BACKEND_URL=/
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  db_data:
