services:
  cloudflared:
    image: cloudflare/cloudflared:2025.7.1
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - frontend
