name: DB Migration Guard

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install backend deps
        working-directory: backend
        run: |
          # Use package-lock.json if present, otherwise run npm install
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json — running npm ci"
            npm ci --no-audit --no-fund
          else
            echo "No package-lock.json — running npm install to produce one"
            npm install --no-audit --no-fund
          fi

      - name: Run migration guard
        run: |
          # If a DATABASE_URL secret is configured, export it; otherwise, run without DB to avoid Prisma P1012
          if [ -n "${{ secrets.DATABASE_URL }}" ]; then
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            echo "DATABASE_URL provided — will run live diff against the database."
          else
            echo "DATABASE_URL not provided — running guard without live diff (schema validate + SQL scan only)."
            unset DATABASE_URL || true
          fi
          chmod +x scripts/*.sh || true
          ./scripts/guard-migrations.sh
